spring:
  application:
    name: product-service

  output:
    ansi:
      enabled: always

  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: password

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

server:
  port: 19093
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/